### ISSUE TITLE
What is "dot" command?

### ISSUE THREAD

**Issue by Gargo** [raineorshine/solgraph#18]
I work in windows

**Comment by morenoh149** [comment]
dot is an open format, you should be able to install graphviz on windows http://www.graphviz.org/download/#windows please update the readme instructions if you are successful. See https://github.com/raineorshine/solgraph/blob/master/package.json#L45 and https://en.wikipedia.org/wiki/DOT_(graph_description_language)

**Comment by vardhmanandroid2015** [comment]
Make sure to add the dot.exe that is present in installed directory for graphviz within path as MSI is not doing so.....Even if that is not recognized then use complete path to use the same command....

**Comment by raineorshine** [comment]
https://en.wikipedia.org/wiki/DOT_(graph_description_language)
