### ISSUE TITLE
Does not support "emit" keyword

### ISSUE THREAD

**Issue by vardhmanandroid2015** [raineorshine/solgraph#19]
It seems like new keyword "emit"added for event does not seem to be handled so require to accommodate this at code level along with all the new keywords added recently...e.g. assert, require & revert

**Comment by vardhmanandroid2015** [comment]
Just think through it & found that changing solidity parser to latest version can help here rather using the specific one.....

**Comment by stefek99** [comment]
Not to duplicate issues, it also does not support `constructor` keyword.

Also here:
![image](https://user-images.githubusercontent.com/249703/41528949-7b262418-72e3-11e8-944f-3a26abc574da.png)

Maybe the way to initialise structs is also out of date?
![image](https://user-images.githubusercontent.com/249703/41528966-8a1ae288-72e3-11e8-8ce3-01dd7a006599.png)

https://ethereum.stackexchange.com/questions/1511/how-to-initialize-a-struct

**Comment by raineorshine** [comment]
Fixed in `v0.3.0`
