### ISSUE TITLE
compliment: this is awesome

### ISSUE THREAD

**Issue by SilentCicero** [raineorshine/solgraph#2]
I'm filing an issue, that issue: why didn't I see this earlier. Awesome work. We should talk, I'm working on a linting system, would love your thoughts and help: https://github.com/weifund/solint

**Comment by raineorshine** [comment]
Cool, I'll check it out! And thanks!!!

I'm leaving this issue open for more compliments 😆

**Comment by Bunjin** [comment]
Another Issue Raine !!!!!!

PLEASE HELP !!!

This is too awesome, I'm going to lose my mind !! :)

**Comment by drandreaskrueger** [comment]
! superb !
