### ISSUE TITLE
Add support for multiple solidity files

### ISSUE THREAD

**Issue by drandreaskrueger** [raineorshine/solgraph#22]
is there a way to combine many .sol sourcefiles into one solgraph PNG?

e.g. could [these 20 contracts](https://github.com/raineorshine/solgraph/issues/21), and their interdependencies, be shown in one large PNG image?

**Comment by raineorshine** [comment]
Yes, this is needed.

Similar to #13.

**Comment by jpantunes** [comment]
This is fixed in 0.2.7.

**Comment by raineorshine** [comment]
@jpantunes It was published as `v0.3.0`. Typically I will bump the version number after merging PR's and before publishing.
