### ISSUE TITLE
Installation failure 

### ISSUE THREAD

**Issue by unboxedtype** [raineorshine/solgraph#25]
Trying to install solgraph, but observe failure.

Linux oberon 4.16.12-300.fc28.x86_64 #1 SMP Fri May 25 21:13:28 UTC 2018
Fedora 28 Workstation Edition

> $ npm --version
> 5.6.0
> 
> $ sudo npm install --save -g solgraph
> ....
> 7518 info lifecycle solgraph@0.2.6~postinstall: solgraph@0.2.6
> 7519 verbose lifecycle solgraph@0.2.6~postinstall: unsafe-perm in lifecycle false
> 7520 verbose lifecycle solgraph@0.2.6~postinstall: PATH: /usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/node-gyp-bin:/usr/\
> lib/node_modules/solgraph/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> 7521 verbose lifecycle solgraph@0.2.6~postinstall: CWD: /usr/lib/node_modules/solgraph
> 7522 silly lifecycle solgraph@0.2.6~postinstall: Args: [ '-c', 'npm run build' ]
> 7523 silly lifecycle solgraph@0.2.6~postinstall: Returned: code: 243  signal: null
> 7524 info lifecycle solgraph@0.2.6~postinstall: Failed to exec postinstall script
> 7525 verbose unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
> 7526 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/solgraph/node_modules/fsevents):
> 7527 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"\
> os":"linux","arch":"x64"})
> 7528 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
> 7528 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
> 7528 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
> 7528 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
> 7529 verbose stack Error: solgraph@0.2.6 postinstall: `npm run build`
> 7529 verbose stack Exit status 243
> 7529 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/index.js:285:16)
> 7529 verbose stack     at emitTwo (events.js:126:13)
> 7529 verbose stack     at EventEmitter.emit (events.js:214:7)
> 7529 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/lib/spawn.js:55:14)
> 7529 verbose stack     at emitTwo (events.js:126:13)
> 7529 verbose stack     at ChildProcess.emit (events.js:214:7)
> 7529 verbose stack     at maybeClose (internal/child_process.js:925:16)
> 7529 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 7530 verbose pkgid solgraph@0.2.6
> 7531 verbose cwd /home/shishkin
> 7532 verbose Linux 4.16.12-300.fc28.x86_64
> 7533 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "-g" "solgraph"
> 7534 verbose node v8.11.2
> 7535 verbose npm  v5.6.0
> 7536 error code ELIFECYCLE
> 7537 error errno 243
> 7538 error solgraph@0.2.6 postinstall: `npm run build`
> 7538 error Exit status 243
> 7539 error Failed at the solgraph@0.2.6 postinstall script.
> 7539 error This is probably not a problem with npm. There is likely additional logging output above.
> 7540 verbose exit [ 243, true ]
>

**Comment by raineorshine** [comment]
Try `sudo npm install --save -g solgraph --unsafe-perm=true --allow-root` (from #15)

**Comment by unboxedtype** [comment]
It works! Thank you.

**Comment by raineorshine** [comment]
Great! I'll add it to the README.
