### ISSUE TITLE
 Cannot find module '@babel/preset-es2015' from '......./node_modules/solgraph'

### ISSUE THREAD

**Issue by eyexx** [raineorshine/solgraph#37]
When I do "npm install solgraph", I got this error.

```
Cannot find module '@babel/preset-es2015' from '/Users/.../.myproject/node_modules/solgraph'
```

What is wrong? 

I hope someone adivise me ! 😭

<img width="1249" alt="2018-08-20 12 17 07" src="https://user-images.githubusercontent.com/31874274/44318822-5cce0500-a473-11e8-8483-6e11575f5207.png">

**Comment by raineorshine** [comment]
Fixed and published in `v0.3.3`
