### ISSUE TITLE
Parse error at uint internal value;

### ISSUE THREAD

**Issue by drandreaskrueger** [raineorshine/solgraph#4]
```
contract Sample
{
    uint internal value;
}
```

results in

`Parse error
{ [SyntaxError: Expected "!=", "!==", "%", "%=", "&", "&&", "&=", "*", "*=", "+", "++", "+=", ",", "-", "--", "-=", "/", "/*", "//", "/=", ";", "<", "<<", "<<=", "<=", "=", "==", "===", ">", ">=", ">>", ">>=", ">>>", ">>>=", "?", "^", "^=", "in", "instanceof", "|", "|=", "||", comment, end of line or whitespace but "v" found. Line: 3, Column: 16]`

**Comment by raineorshine** [comment]
Thanks for reporting! Thanks for taking the time to isolate it. Simple parse error in [solidity-parser](https://github.com/ConsenSys/solidity-parser).

I opened a pull request for it: https://github.com/ConsenSys/solidity-parser/pull/2
