### ISSUE TITLE
parse error with abi coder

### ISSUE THREAD

**Issue by liron-navon** [raineorshine/solgraph#47]
unable to parse line with abi coder

<img width="777" alt="Screenshot 2022-10-20 at 11 15 30" src="https://user-images.githubusercontent.com/18119833/196908394-b422f6c6-5036-449f-8859-0b3226a592aa.png">

**Comment by raineorshine** [comment]
Hi, thanks for reporting. The parser needs to be updated from [solidity-parser-sc](https://github.com/sc-forks/solidity-parser) to [solidity-parser-antlr](https://github.com/federicobond/solidity-parser-antlr) or another parser that supports the latest `solc`. I am no longer actively working on this project myself but I would be happy to support a PR from anyone who is interested in contributing.

**Comment by raineorshine** [comment]
Fixed in `v1.0.0`. Special thanks to @yellowBirdy.
