### ISSUE TITLE
Message on successful execution

### ISSUE THREAD

**Issue by shayanb** [raineorshine/solgraph#9]
This is a suggestion and not a bug report.
It'd be nice to get a success message when the execution is successful.

some discussion here: https://github.com/raineorshine/solgraph/issues/6#issuecomment-293615025

**Comment by raineorshine** [comment]
Thank you for the suggestion. Though it may seem odd, the best practice in the unix world is to print nothing on success. There are [exit codes](https://shapeshed.com/unix-exit-codes) to indicate the status of the execution.
